### ISSUE TITLE
how to make divegrind automatically, where is the the option?

### ISSUE THREAD

**Issue by Speedrunner50** [Mupen64-Rewrite/SM64LuaRedux#18]
![image](https://github.com/Mupen64-Rewrite/SM64LuaRedux/assets/105159366/03dde3c4-cc27-4fbf-8853-2e1587f5a442)
can someone show me where is it? in screenshot pls

**Comment by Aurumaker72** [comment]
https://github.com/Mupen64-Rewrite/SM64LuaRedux/wiki/Experiments#auto-grind-startstop

![grafik](https://github.com/Mupen64-Rewrite/SM64LuaRedux/assets/48759429/1af95335-64c4-4fc6-b112-41e7c5d21f21)


Note that this feature is an experiment and produces very suboptimal results.
